### ISSUE TITLE
Working iOS example

### ISSUE THREAD

**Issue by mfentross** [aleph7/caffe#3]
It would be great if someone could commit a working example for iOS, since some (including me) are having problems with this.

**Comment by noradaiko** [comment]
Also tests needed.
The compiling it succeeded though it may be not working correctly.
I'm trying to implement an example of cpp_classification, but it outputs incorrect classification results.

**Comment by noradaiko** [comment]
Hey, I opened source the iOS example [here](https://github.com/noradaiko/caffe-ios-sample).
Check it out.

@aleph7 
It can classify images with CaffeNet correctly.
But it outputs incorrect result if you try with GoogLeNet model.
Could you point out the problem?

**Comment by aleph7** [comment]
@noradaiko 👍

What seems to be the problem?

**Comment by noradaiko** [comment]
I get different result between cpp_classification of Caffe example and the iOS version of it.

For example, I trained [Caltech101](http://www.vision.caltech.edu/Image_Datasets/Caltech101/) and used it on both classifier.

The result of Caffe example:
```
$ $CAFFE_HOME/build/examples/cpp_classification/classification.bin deploy.prototxt caltech101.caffemodel test_mean.binaryproto labels.txt data/airplanes/image_0031.jpg
---------- Prediction for data/airplanes/image_0031.jpg ----------
23.1475 - "6 airplanes"
8.1355 - "28 crab"
7.8853 - "63 mandolin"
7.8852 - "52 helicopter"
7.1359 - "83 scorpion"
```

The result of iOS version of classification.bin:
```
2015-07-18 19:15:39.490 CaffeApp[32428:6146658] label: 6 airplanes, prob: 17.93211
2015-07-18 19:15:39.491 CaffeApp[32428:6146658] label: 83 scorpion, prob: 7.606801
2015-07-18 19:15:39.492 CaffeApp[32428:6146658] label: 28 crab, prob: 6.97776
2015-07-18 19:15:39.492 CaffeApp[32428:6146658] label: 63 mandolin, prob: 6.902995
2015-07-18 19:15:39.492 CaffeApp[32428:6146658] label: 101 wrench, prob: 6.778043
```

The top-1 is correct classification though different to the former.
Why does it occur even though the both code and model are completely same?

**Comment by LuisTbx** [comment]
Hello @aleph7 and @noradaiko 

I also found a similar behaviour while using the sample application. I am using network in network model fine-tuned on my own data. Do you have some hints about where the problem could be? (results differ from the ones given by C++). I had a look to the classifier code and seems to me there is nothing missing.

Best regards,

**Comment by LuisTbx** [comment]
The issue is solved now, it happens that by default iOS loads UIImages in RGBA, while the preprocessing does BGRA2BGR. so by forcing the image to be in BGRA it fixed the problem.

**Comment by noradaiko** [comment]
Great! I'm gonna look into it.

**Comment by noradaiko** [comment]
Confirmed @LuisTbx's solution fixed the problem.
I will apply the change into my example.
Thanks for your report!

@aleph7 Sorry, it was my fault.
